const sampleData = {
  products: [
    {
      name: 'Glora Lux',
      slug: 'glora-lux',
      category: "Bioluminescent",
      description: 'A bioluminescent plant with glowing blue-green leaves featuring intricate patterns.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 58.99,
      brand: 'Nostromo7',
      rating: 4.4,
      numReviews: 10,
      stock: 6,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Nexum Radi',
      slug: 'nexum-radi',
      category: "Sentient",
      description: 'This plant boasts vibrant glowing red and purple spiral-shaped leaves with transparent sections that emit soft light.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 210.9,
      brand: 'Yutani-Corp',
      rating: 4.1,
      numReviews: 8,
      stock: 14,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Cyanara Prime',
      slug: 'cyanara-prime',
      category: "BioTech",
      description: 'A sleek plant with metallic silver leaves glowing at the edges in cyan.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 34.45,
      brand: 'Nostromo7',
      rating: 4.8,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Auralis Aer Flora',
      slug: 'auralis-aer-flora',
      category: "Bioluminescent",
      description: 'A bioluminescent plant with glowing neon green and purple leaves.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Nostromo7',
      rating: 3.8,
      numReviews: 5,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Rosia Bloom',
      slug: 'rosia-bloom',
      category: "Bioluminescent",
      description: 'This elegant plant features glowing pink bioluminescent leaves that emit a soft radiant light.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Nostromo7',
      rating: 4.7,
      numReviews: 18,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Solaris Flare',
      slug: 'solaris-flare',
      category: "Sentient",
      description: 'An intelligent plant with glowing orange leaves that radiate warmth.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Yutani-Corp',
      rating: 4.6,
      numReviews: 12,
      stock: 2,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Luminara Aurea',
      slug: 'luminara aurea',
      category: "Sentient",
      description: 'A captivating plant with golden yellow bioluminescent leaves that emit a soft, vibrant glow',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Yutani-Corp',
      rating: 4.0,
      numReviews: 12,
      stock: 3,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
